name: ArangoDBInterface
version: "2020.04.15"
license: "GPL-2.0-or-later"
date: 2020-04-15
description: |
    An interface to ArangoDB

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "JSON"
      version: ">= 1.2.0"
      url: "https://gap-packages.github.io/json/"
    - name: "ToolsForHomalg"
      version: ">= 2018.11.30"
      url: "https://homalg-project.github.io/homalg_project/ToolsForHomalg/"
    - name: "HomalgToCAS"
      version: ">= 2018.11.30"
      url: "https://homalg-project.github.io/homalg_project/HomalgToCAS/"
    - name: "IO_ForHomalg"
      version: ">= 2017.07.01"
      url: "https://homalg-project.github.io/homalg_project/IO_ForHomalg/"

www: https://homalg-project.github.io/ArangoDBInterface
readme: README.md
packageinfo: https://homalg-project.github.io/ArangoDBInterface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/ArangoDBInterface/releases/download/v2020.04.15/ArangoDBInterface-2020.04.15.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    ArangoDB, arangosh, interface.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bar20</span>]   <b class='BibAuthor'>Barakat, M.</b>,
     <i class='BibTitle'>ArangoDBInterface, An interface to ArangoDB,
             Version 2020.04.15</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/ArangoDBInterface">https://homalg-project.github.io/ArangoDBInterface</a></span>.
    </p>
    

bibtex: |
    @misc{ ArangoDBInterface2020.04.15,
      author =           {Barakat, M.},
      title =            {{ArangoDBInterface}, An interface to ArangoDB, {V}ersion 2020.04.15},
      month =            {Apr},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href {https://homalg-project.github.io/ArangoDBInterface} {\texttt{https://homalg-project.github.io/}\discretionary {}{}{}\texttt{ArangoDBInterface}}},
      keywords =         {ArangoDB; arangosh; interface},
      printedkey =       {Bar20}
    }

