name: ArangoDBInterface
version: "2025.12-01"
license: "GPL-2.0-or-later"
date: 2025-12-23
description: |
    A GAP interface to ArangoDB

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

GAP: ">= 4.13.0"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "JSON"
      version: ">= 1.2.0"
      url: "https://gap-packages.github.io/json/"
    - name: "ToolsForHomalg"
      version: ">= 2018.11.30"
      url: "https://homalg-project.github.io/pkg/ToolsForHomalg"
    - name: "HomalgToCAS"
      version: ">= 2018.11.30"
      url: "https://homalg-project.github.io/pkg/HomalgToCAS"
    - name: "IO_ForHomalg"
      version: ">= 2017.07.01"
      url: "https://homalg-project.github.io/pkg/IO_ForHomalg"

www: https://homalg-project.github.io/pkg/ArangoDBInterface
readme: README.md
packageinfo: https://homalg-project.github.io/ArangoDBInterface/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/ArangoDBInterface/releases/download/v2025.12-01/ArangoDBInterface-2025.12-01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/ArangoDBInterface/releases/download/v2025.12-01/ArangoDBInterface-2025.12-01.zip

pdf: https://github.com/homalg-project/ArangoDBInterface/releases/download/v2025.12-01/ArangoDBInterface-2025.12-01.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    ArangoDB, arangosh, interface.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bar23</span>]   <b class='BibAuthor'>Barakat, M.</b>,
     <i class='BibTitle'>ArangoDBInterface, A GAP interface to ArangoDB,
             Version 2025.12-01</i>
     (<span class='BibYear'>2-23</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/ArangoDBInterface">https://homalg-project.github.io/pkg/ArangoDBInterface</a></span>.
    </p>
    

bibtex: |
    @misc{ ArangoDBInterface,
      author =           {Barakat, M.},
      title =            {{ArangoDBInterface},  {A  GAP  interface to ArangoDB},
                          {V}ersion 2025.12\texttt{\symbol{45}}01},
      month =            {5\texttt{\symbol{45}}},
      year =             {2\texttt{\symbol{45}}23},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/ArangoDBInterface}
                          {\texttt{https://homalg\texttt{\symbol{45}}project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{ArangoDBInterface}}},
      keywords =         {ArangoDB; arangosh; interface},
      printedkey =       {Bar23}
    }

